### PR TITLE
Missing exports condition for svelte

### PR DESCRIPTION
**Pull request by Silvallis**
```bash
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-vertical-timeline@1.0.0

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

Got this error message when trying it out. Tried to follow the steps and works but probably should be tested by you. And I ran audit fix to remove some vulnerabilities.

### CODE REVIEW

**Review by K-Sato1995 — CHANGES_REQUESTED** [review]
@Silvallis 
Thanks! Appreciate it a lot🙏

Just one thing tho! Could u plz remove the `package-lock.json` since the project uses `yarn`? Thanks in advance!

**Comment by Silvallis** [comment]
Never used yarn before and the docs only mention where to add the export setting in the package.json, maybe you could modify it so it also works with yarn?

**Comment by K-Sato1995** [comment]
>Never used yarn before and the docs only mention where to add the export setting in the package.json, maybe you could modify it so it also works with yarn?


@Silvallis 

sorry for the late replay! yeah ill work on it later:)

**Comment by westerandr** [comment]
@K-Sato1995 any progress on this please?

**Comment by K-Sato1995** [comment]
@Silvallis 
Thank you for ur contribution!🙏

@westerandr 

Thank you for the reminder🙏

**Review by K-Sato1995 — APPROVED** [review]
should be good

**Pull request merged**
